require "httparty"
require "query"
require "amazon/ecs"
#require "aseo_db"
require "aseo_spider/version"
require "aseo_spider/baidu_spider"
require "aseo_spider/youku_spider"
require "aseo_spider/amazon_spider"
